name: 🐛 Bug Report
description: Report a bug in LazySSH
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the essential details below.
  
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug in simple terms
      placeholder: LazySSH crashed when I tried to connect to...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      description: Steps to reproduce the issue
      placeholder: |
        1. Run lazyssh
        2. Try to connect to...
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Your setup
      description: OS, Python version, and LazySSH version
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.11.5
        - LazySSH: 1.3.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs (optional)
      description: Any error messages or logs that might help
      render: shell 