name: 🚀 Feature Request
description: Suggest a new feature or enhancement for LazySSH
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Tell us what you'd like to see.

  - type: textarea
    id: description
    attributes:
      label: What feature would you like?
      description: Describe the feature you'd like to see added
      placeholder: "I would like LazySSH to support..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Why would this be useful?
      description: Explain how you would use this feature
      placeholder: "This would help me to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered (optional)
      description: Any workarounds you've tried?
      placeholder: "I've tried... but it doesn't work because..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority (optional)
      description: How important is this to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Critical for my workflow
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Would you like to help? (optional)
      description: We'd love your help if you're interested!
      options:
        - label: I'm willing to submit a pull request for this feature
        - label: I can help with testing
        - label: I can help with documentation 